name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REPO_URI

      # Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t $ECR_REPO_URI:latest .
          docker tag  $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG

      # Push Images to ECR
      - name: Push Docker Images
        run: |
          docker push $ECR_REPO_URI:latest
          docker push $ECR_REPO_URI:$IMAGE_TAG

      # Download Task Definition
      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition YOUR_TASK_DEFINITION_FAMILY \
            --query taskDefinition \
            > taskdef.json

      # Update Task Definition with new image
      - name: Fill in new image ID
        run: |
          sed -i "s|\"image\": \".*\"|\"image\": \"$ECR_REPO_URI:$IMAGE_TAG\"|g" taskdef.json

      # Register new Task Definition
      - name: Register updated task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://taskdef.json

      # Force new ECS Deployment
      - name: Force new deployment on ECS
        run: |
          aws ecs update-service \
            --cluster YOUR_CLUSTER_NAME \
            --service YOUR_SERVICE_NAME \
            --force-new-deployment

      # Completed
      - name: Done
        run: |
          echo "ðŸš€ Deployed version: $IMAGE_TAG"
