name: Deploy to AWS ECR & ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REPO_URI

      # Build & Tag Docker Image
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t $ECR_REPO_URI:latest .
          docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPO_URI:latest
          docker push $ECR_REPO_URI:${IMAGE_TAG}

      # Prepare updated task definition
      - name: Create new task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition devops_demo_td \
            --query "taskDefinition.{family:family, taskRoleArn:taskRoleArn, executionRoleArn:executionRoleArn, networkMode:networkMode, 
                     containerDefinitions:containerDefinitions, requiresCompatibilities:requiresCompatibilities, cpu:cpu, memory:memory}" \
            > taskdef.json


          sed -i "s|\"image\": \".*\"|\"image\": \"${ECR_REPO_URI}:${IMAGE_TAG}\"|" taskdef.json

      # Register new ECS Task Definition
      - name: Register task definition
        id: register
        run: |
          NEW_TASK_DEF=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "NEW_TASK_DEF=$NEW_TASK_DEF" >> $GITHUB_ENV

      # Update ECS service with new task definition
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster devops_demo_cluster \
            --service devops_demo_td-service-e22zy8av \
            --task-definition $NEW_TASK_DEF \
            --force-new-deployment

      # Output Image Tag
      - name: Finished
        run: |
          echo "Deployed Image Tag: $IMAGE_TAG"
